### ISSUE TITLE
Failure on inserting a node with duplicate id

### ISSUE THREAD

**Issue by OleksiyRudenko** [lempiy/react-direct-graph#3]
STR:
1. Navigate to https://lempiy.github.io/react-direct-graph/
2. On **Graph editing** click either node
3. Type a node id in equal to any already existing node id

Expected effect: unknown

Actual effect: page renders blank, dev console reports `Duplicate id ...`

User anticipated effect: friendlier UX, e.g. UI error report or moving a node to a designated location (i.e. delete node with given id re-linking nodes as on user action node deletion and adding a new node as expected with now unique id)

**Comment by lempiy** [comment]
Since this is a library it's up to user how to handle case with duplicate id. Mentioned error, occurs within components code (not in example App) because user didn't satisfied one of the main props requirements (ID uniqueness). Finger typing node IDs is absolutely fancy case for production, because usually IDs are generated by machine, maybe it will be better to automatically set ID upon insert in our example ?

**Comment by OleksiyRudenko** [comment]
AutoID would make the demo less confusing.
Another option might be splitting between id and visual content, where content by default equals id.
The above is just for your consideration, complicating the logic might be excessive if for demo purposes only.

**Comment by lempiy** [comment]
@OleksiyRudenko Added autoid with simple counter
